### ISSUE TITLE
Tooltip does not work

### ISSUE THREAD

**Issue by michi20** [MarcDiethelm/jQuery-Shorten#1]
Hi Marc,

I tried to use your plugin and it works very well except for the tooltip part. I have set the tooltip-property to true but no tooltip is shown. Any ideas? 

I have not found anything related to tooltips in your js-code.

Thanks!

**Comment by MarcDiethelm** [comment]
Gee you're right! I somehow forgot to add this when I re-wrote the plugin! :)

It's fixed now. Tooltips are on by default (if the text was shortened).

Thanks for the comment.
