### ISSUE TITLE
Not working on Firefox Beta 4

### ISSUE THREAD

**Issue by TomCaserta** [MarcDiethelm/jQuery-Shorten#5]
I assume this is meant to work for this. Since this is the only browser I really need this plugin to work on is there anyway you could update or fix it? 

Thanks!

**Comment by MarcDiethelm** [comment]
Hmm, I just tested in Fx Beta 9 and 10 on Linux and it works perfectly for me.

Can you give me a little more detail or maybe link your code in http://jsfiddle.net/?

**Comment by MarcDiethelm** [comment]
Please check out test.html in the test folder... Does it work there?

**Comment by TomCaserta** [comment]
Yep seems to be working on that one :o

Wasnt working for me on the demo page though which is why I hadnt bothered to download and actually try it :)

Thanks, saved alot of work!

**Comment by TomCaserta** [comment]
Hmm Im not sure if ive misunderstood what this does. Can I make it use overflow-y "properties" as in how it does it. So basically it fills the content until its going out the box at the bottom of it. At the moment its removing my br's and its just going on one line... (Edit what I meant to mean is, is there anyway I can make it multiline at all?)

I can give an example of what it is doing if needed.

**Comment by MarcDiethelm** [comment]
Sorry, the plugin functionality is strictly single-line and is highly optimized for that purpose. In a manner it's a CSS3 text-overflow shim.  You may want to have a look at the 'ThreeDots' jQuery plugin.

The demo page is working again by the way. Thanks for alerting me to that problem!!
