### ISSUE TITLE
Tooltip doesn't get updated sometimes

### ISSUE THREAD

**Issue by chrisbartley** [MarcDiethelm/jQuery-Shorten#8]
First, thanks for this plugin.  

I found an issue with the tooltip, however.  It doesn't get updated if the text was once too long (and thus shortened), but then changes such that its new length fits within the target width.  The problem is that the title attribute isn't removed in the if block which checks the length.  Simply adding `$this.removeAttr("title");` fixes it.  Here it is in context:

``` javascript
if (origLength < targetWidth) {
  //$c.log("nothing to do");
  $this.text(text);
  $this.removeAttr("title");
  this.style.visibility = "visible";

  $this.data(info_identifier, info);

  return true;
}
```

Chris

**Comment by MarcDiethelm** [comment]
Fixed and released as 0.9.0. It took a while... My sincere apologies. Thanks a lot for contributing!
